version: "3.3"

services:
#-----blog service----
  blog:
    extends:
      file: ./blog/docker-compose.yml
      service: web
    env_file:
      - .env
  blogdb:
    extends:
      file: ./blog/docker-compose.yml
      service: database

  #-----user service------
  user:
    extends:
      file: ./user/docker-compose.yml
      service: web
    env_file:
      - .env
  userdb:
    extends:
      file: ./user/docker-compose.yml
      service: database
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile

    ports:
      - "${Port}:80"

volumes:
  blog_db:
    external: true
  user_db:
    external: true